image: "python:3.7"

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
    - python -m flake8

black:
  stage: Static Analysis
  script:
    - python -m black --check .

test:
  stage: Test
  script:
  - pip install -r requirements-dev.txt
  - python -m pytest ./tests
