[tool.black]
exclude = '/(venv*|.tox)'


[tool.pytest.ini_options]
markers = [
    "epics_protocol: (EpicsProtocol) The protocol used for the test",
    "schema: (str) The streaming-data-type of the test",
    "serialiser_update_period_ms: (int) Update period (ms) for any created Serialiser",
]
testpaths = [
    "tests",
]
addopts = "-s"
junit_family = "xunit2"
